#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlprotocol_py
  
  bl_listgen \
    -d ../xlprotocol_py \
    -1L  \
    -u $DVCZ_UDIR \
    -X cover \
    -X htmlcov \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
