#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlprotocol_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ xlprotocol tests/test_basics.py setup.py
else
  echo "DEV_BASE is not defined"
fi
